kind: Pod
apiVersion: v1
metadata:
  name: task-pv-pod
spec:
  volumes:
    - name: my-volume
      persistentVolumeClaim:
       claimName: my-pv-claim
  containers:
    - name: task-pv-container
      image: nginx
      ports:
        - containerPort: 8080
          name: "http-server"
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: my-volume
